-- Open-castle Great Hall goal: the codes whose progress feeds the goal panel,
-- and how slot_data targets map. Hand-authored (the section/item codes are
-- stable); not regenerated by tools/generate.py.
--
-- Progress is read from state the tracker already holds: spell item toggles,
-- the per-tier card counters, and the cleared level-completion / duel / match
-- locations. Targets come from slot_data (open_castle_goal_*), captured in
-- onClear. Vanilla seeds send no targets, so the overall light stays off.

GOAL_SPELL_CODES = {
	"Alohomora", "Diffindo", "Flipendo", "Lumos",
	"Rictusempra", "Skurge", "Spongify",
}

GOAL_CARD_COUNTERS = { "bronze_cards", "silver_cards", "gold_cards" }

-- The 12 level objectives (apworld LevelCompletions, ids 5760700..5760711).
GOAL_LEVEL_CODES = {
	"@Boomslang Level/Complete/Complete",
	"@Bicorn Level/Complete/Complete",
	"@Goyle Level/Complete/Complete",
	"@Forbidden Forest/Complete/Complete",
	"@Chamber of Secrets/Complete/Complete",
	"@Whomping Willow/Complete/Complete",
	"@Slytherin Common Room/Complete/Complete",
	-- These four challenges colocate Complete with Beat Par Time under a
	-- "Completion" group node, so the path's middle segment is the group.
	"@Rictusempra Challenge/Completion/Complete",
	"@Skurge Challenge/Completion/Complete",
	"@Diffindo Challenge/Completion/Complete",
	"@Spongify Challenge/Completion/Complete",
	"@Gryffindor Challenge/Complete/Complete",
}

-- All ten duels colocate under a "Duels" group node, so the path's middle
-- segment is the group.
GOAL_DUEL_CODES = {
	"@Duelling Club/Duels/Duel Rank 1",
	"@Duelling Club/Duels/Duel Rank 2",
	"@Duelling Club/Duels/Duel Rank 3",
	"@Duelling Club/Duels/Duel Rank 4",
	"@Duelling Club/Duels/Duel Rank 5",
	"@Duelling Club/Duels/Duel Rank 6",
	"@Duelling Club/Duels/Duel Rank 7",
	"@Duelling Club/Duels/Duel Rank 8",
	"@Duelling Club/Duels/Duel Rank 9",
	"@Duelling Club/Duels/Duel Rank 10",
}

-- All six matches colocate under a "Quidditch Matches" group node.
GOAL_QUID_CODES = {
	"@Quidditch/Quidditch Matches/Match 1 (Hufflepuff)",
	"@Quidditch/Quidditch Matches/Match 2 (Ravenclaw)",
	"@Quidditch/Quidditch Matches/Match 3 (Slytherin)",
	"@Quidditch/Quidditch Matches/Match 4 (Hufflepuff)",
	"@Quidditch/Quidditch Matches/Match 5 (Ravenclaw)",
	"@Quidditch/Quidditch Matches/Match 6 (Slytherin)",
}
