-- Open-castle Great Hall goal: the codes whose progress feeds the goal panel,
-- and how slot_data targets map. Hand-authored (the section/item codes are
-- stable); not regenerated by tools/generate.py.
--
-- Progress is read from state the tracker already holds: spell item toggles,
-- the per-tier card counters, and the cleared level-completion / duel / match
-- locations. Targets come from slot_data (open_castle_goal_*), captured in
-- onClear. Vanilla seeds send no targets, so the overall light stays off.

GOAL_SPELL_CODES = {
	"Alohomora", "Diffindo", "Flipendo", "Lumos",
	"Rictusempra", "Skurge", "Spongify",
}

GOAL_CARD_COUNTERS = { "bronze_cards", "silver_cards", "gold_cards" }

-- The 12 level objectives (apworld LevelCompletions, ids 5760700..5760711).
GOAL_LEVEL_CODES = {
	"@Boomslang Level/Complete/Complete",
	"@Bicorn Level/Complete/Complete",
	"@Goyle Level/Complete/Complete",
	"@Forbidden Forest/Complete/Complete",
	"@Chamber of Secrets/Complete/Complete",
	"@Whomping Willow/Complete/Complete",
	"@Slytherin Common Room/Complete/Complete",
	"@Rictusempra Challenge/Complete/Complete",
	"@Skurge Challenge/Complete/Complete",
	"@Diffindo Challenge/Complete/Complete",
	"@Spongify Challenge/Complete/Complete",
	"@Gryffindor Challenge/Complete/Complete",
}

GOAL_DUEL_CODES = {
	"@Duelling Club/Duel Rank 1/Duel Rank 1",
	"@Duelling Club/Duel Rank 2/Duel Rank 2",
	"@Duelling Club/Duel Rank 3/Duel Rank 3",
	"@Duelling Club/Duel Rank 4/Duel Rank 4",
	"@Duelling Club/Duel Rank 5/Duel Rank 5",
	"@Duelling Club/Duel Rank 6/Duel Rank 6",
	"@Duelling Club/Duel Rank 7/Duel Rank 7",
	"@Duelling Club/Duel Rank 8/Duel Rank 8",
	"@Duelling Club/Duel Rank 9/Duel Rank 9",
	"@Duelling Club/Duel Rank 10/Duel Rank 10",
}

GOAL_QUID_CODES = {
	"@Quidditch/Match 1 (Hufflepuff)/Match 1 (Hufflepuff)",
	"@Quidditch/Match 2 (Ravenclaw)/Match 2 (Ravenclaw)",
	"@Quidditch/Match 3 (Slytherin)/Match 3 (Slytherin)",
	"@Quidditch/Match 4 (Hufflepuff)/Match 4 (Hufflepuff)",
	"@Quidditch/Match 5 (Ravenclaw)/Match 5 (Ravenclaw)",
	"@Quidditch/Match 6 (Slytherin)/Match 6 (Slytherin)",
}
