-- Engine map name (Caps form of Level.Outer.Name, as the mod sends it over
-- LEVEL and mirrors into AP Data Storage) -> tab path to activate, as
-- { outer group tab, leaf map tab }. Both are activated in order so a nested
-- tab focuses correctly. Hand-authored: engine map names are not present in
-- the apworld, so this is not regenerated by tools/generate.py.
--
-- Level -> region comes from APCardWatcher.uc's level-completion index
-- (the authoritative source). Tab titles match layouts/tabs.json exactly.
LEVEL_TO_TAB = {
	["ENTRYHALL_HUB"]      = { "Castle", "Entry Hall" },
	["GRANDSTAIRCASE_HUB"] = { "Castle", "Grand Staircase" },
	["GROUNDS_HUB"]        = { "Castle", "Castle Exterior" },
	["GROUNDS_NIGHT"]      = { "Castle", "Castle Exterior" },

	["ADV1WILLOW"]         = { "Levels", "Whomping Willow" },
	["ADV3DUNGEONQUEST"]   = { "Levels", "Bicorn Level" },
	["ADV4GREENHOUSE"]     = { "Levels", "Boomslang Level" },
	["ADV6GOYLE"]          = { "Levels", "Goyle Level" },
	["ADV7SLYTHCOMROOM"]   = { "Levels", "Slytherin Common Room" },
	["ADV8FOREST"]         = { "Levels", "Forbidden Forest" },
	["ADV9ARAGOG"]         = { "Levels", "Forbidden Forest" },
	-- Chamber of Secrets is three engine maps but one tracker region/tab, so
	-- all three keep the player on the single "Chamber of Secrets" tab.
	["ADV11ACORRIDOR"]     = { "Levels", "Chamber of Secrets" },
	["ADV11BSECRETS"]      = { "Levels", "Chamber of Secrets" },
	["ADV12CHAMBER"]       = { "Levels", "Chamber of Secrets" },

	["CH6WIZARDCARD"]      = { "Levels", "Gold Card Room" },

	["CH1RICTUSEMPRA"]     = { "Spell challenges", "Rictusempra" },
	["CH2SKURGE"]          = { "Spell challenges", "Skurge" },
	["CH3DIFFINDO"]        = { "Spell challenges", "Diffindo" },
	["CH4SPONGIFY"]        = { "Spell challenges", "Spongify" },
	["CH7GRYFFINDOR"]      = { "Spell challenges", "Gryffindor" },
}

-- Fallback for any map name not in LEVEL_TO_TAB (front-end, intro, cutscene
-- maps): land on the Entry Hall. An empty/unset level value switches nothing.
LEVEL_TO_TAB_DEFAULT = { "Castle", "Entry Hall" }
