Tracker:AddLocations("locations/BeanRewardRoom.json")
Tracker:AddLocations("locations/Bicorn Level.json")
Tracker:AddLocations("locations/Boomslang Level.json")
Tracker:AddLocations("locations/Castle Exterior.json")
Tracker:AddLocations("locations/Chamber of Secrets.json")
Tracker:AddLocations("locations/Diffindo Challenge.json")
Tracker:AddLocations("locations/Entry Hall.json")
Tracker:AddLocations("locations/Forbidden Forest.json")
Tracker:AddLocations("locations/Gold Card Room.json")
Tracker:AddLocations("locations/Goyle Level.json")
Tracker:AddLocations("locations/Grand Staircase.json")
Tracker:AddLocations("locations/Gryffindor Challenge.json")
Tracker:AddLocations("locations/Rictusempra Challenge.json")
Tracker:AddLocations("locations/Skurge Challenge.json")
Tracker:AddLocations("locations/Slytherin Common Room.json")
Tracker:AddLocations("locations/Spongify Challenge.json")
Tracker:AddLocations("locations/Whomping Willow.json")
